# Generated by Django 6.0 on 2025-12-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
